version: '3.3'

services:
  flask:
    build: flask-app
    environment:
      MONGO_HOST: mongo
      MONGO_DB: dmler
      RABBIT_HOST: rabbit
      RABBIT_PORT: '5672'
    ports:
      - '127.0.0.1:8080:8080'
    secrets:
      - flask_key
  
  mailer:
    build: mail-sender
    environment:
      RABBIT_HOST: rabbit
      RABBIT_PORT: '5672'
    secrets:
      - mailer_smtp

  mongo:
    image: 'mongo'

  rabbit:
    image: 'rabbitmq'
    # ports:

secrets:
  flask_key:
    file: secrets/flask_key
  mailer_smtp:
    file: secrets/mailer_smtp
